export const Types = {
  ADD_NUMBER: "ADD_NUMBER",
  SUB_NUMBER: "SUB_NUMBER",
  USER_REGISTERED: "USER_REGISTERED",
  USER_REGISTERED_FAILED: "USER_REGISTERED_FAILED",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGIN: "USER_LOGIN",
};
